name: Build for gp

run-name: ${{ github.actor }} build for gp

on: [workflow_call]

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.ACTIONS_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
          cache: npm

      - name: Installing dependences
        run: npm ci

      - name: Building app
        run: npm run build

        if: success()
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: build/
          retention-days: 30
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build
