name: New release

run-name: ${{ github.actor }} create new release

on:
  push:
    tags:
      - 'v\d+'

permissions:
  contents: write
  issues: write

jobs:
  tests:
    uses: ./.github/workflows/tests-ci-for-pr.yml

  create-branch-for-release:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create release branch
        run: |
          git checkout -b release-${{ github.ref_name }}
          git push -u origin release-${{ github.ref_name }}

  create-registry:
    runs-on: ubuntu-latest
    needs: create-branch-for-release
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create description for tag
        id: tag
        run: |
          cur_tag=${{ github.ref_name }} 
          prev_tag=$(git describe --tags --abbrev=0 ${cur_tag}^)
          echo "current_tag=${cur_tag}" >> "$GITHUB_OUTPUT"
          echo "previous_tag=${prev_tag}" >> "$GITHUB_OUTPUT"
          echo "author=${{ github.actor }}" >> $GITHUB_OUTPUT
          echo "date=$(date +'%d.%m.%Y %H:%M:%S')" >> $GITHUB_OUTPUT

      - name: Generate Changelog
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}
          writeToFile: false
      - name: Create issue
        uses: imjohnbo/issue-bot@3d96848fb5e9a4a473bb81ae62b4b4866a56e93a
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
        with:
          assignees: ${{steps.outputs.tag.current_tag}}
          labels: "Release"
          title: New realease ${{ github.ref_name }}
          body: |
            ## This is a new release - ${{ github.ref_name }}
            
            Creation time - ${{ steps.tag.outputs.date }}
            The author of the release is -  ${{ github.actor }}

            Changelog: 
            ${{ steps.changelog.outputs.changes }}
          pinned: false
          close-previous: false

  deploy:
    uses: ./.github/workflows/deploy.yml
    needs: create-registry

