name: Prepare for pr

run-name: ${{ github.actor }} run tests

on: [pull_request, workflow_call]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
      - name: Installing dependences
        run: npm ci
      - name: Run unit tests
        run: npm run test
        if: always()
        with:
          name: unit-res
          path: test-report.html
          retention-days: 30

  e2e-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
      - name: Installing dependences
        run: npm ci
      - name: Install playwright for e2e tests
        run: npx playwright install --with-deps chromium
      - name: Run e2e tests
        run: npm run ci:e2e
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: e2e-res
          path: playwright-report/
          retention-days: 30

